### ISSUE TITLE
Some plugins versions are removed by refreshVersions

### ISSUE THREAD

**Issue by LouisCAD** [jmfayard/gradle-dependencies-plugins#144]
Permalink to reproducing project: https://github.com/LouisCAD/update-legacy-android-project/tree/66f7e854f33593c2a990f40f8f12abbaf66f15f1

`plugin.android=3.5.0` and `plugin.de.fayard.dependencies=0.5.0` are ditched by the `refreshVersion` Gradle task while they are used.

I need to find where I can get the fact that they are used and that they get their version from `versions.properties` to include them when running `refreshVersions`.

**Comment by jmfayard** [comment]
Hold on on this, it's part of the larger discussion on how to finalize the `versions.properties` file format and its configuration. I am not blocked anymore for my tutorial, thanks a lot!

**Comment by LouisCAD** [comment]
Well, I thought this case was handled correctly, so it's still an issue I
need to fix regardless of the format (especially about dropping the
version. suffix)

**Comment by jmfayard** [comment]
Ah ok
